/// <reference types="cypress" />
import { loginPage } from '../../../util.js';

it('Deve criar ScalingGroup', () =>{
    loginPage()
    cy.server() 
    cy.route('/ucloud/rest/scaling-group').as('scaling-group')
    cy.get('#liSCG > a').click()  
    cy.wait('@scaling-group' , {
        requestTimeout: 21000
    })
    cy.route('/ucloud/rest/keyPair').as('keyPair')
    cy.get('[ng-hide="sgsCtrl.hideBtns || !sgsCtrl.isOpenstack"]').click({force: true})
    cy.wait('@keyPair', {
        requestTimeout: 20000
    })
    cy.get('#select-input-type-template > .form-group > .form-control').select('Ucloud input', {force: true})
    cy.wait(1000)
    cy.get('#select-vdc-ucloud-input > .form-group > .form-control').select('matheus1603Open', {force: true})
    cy.get('#tNext').click()
    cy.get('#step5 > :nth-child(1) > .form-control').type('matheus')
    cy.get(':nth-child(2) > tr > [style="padding-left:0"] > .form-control').select('CentOS-7-x86_64')
    cy.get(':nth-child(2) > tr > [style="padding-right:0"] > .form-control').select('C1-1vCPU-2GB-RAM')
    cy.get(':nth-child(4) > tr > [style="padding-left:0"] > .form-control').select('172.26.0.0/16 / services-subnet -')
    // cy.get(':nth-child(4) > tr > [style="padding-right:0"] > .form-control').select('coutopen')
    // cy.get('#step5 > :nth-child(3) > .form-control').select('2020')
    cy.get('#tNext').click()
    cy.get('.active > :nth-child(1) > :nth-child(1) > .form-control').type('matheus')
    cy.get('.active > :nth-child(1) > :nth-child(2) > .form-control').select('public-fip')
    cy.get('.active > :nth-child(1) > :nth-child(4) > .form-control').select('HTTPS')
    cy.get('.active > :nth-child(1) > :nth-child(5) > .form-control').type('80')
    cy.get(':nth-child(7) > .form-control').select('HTTPS')
    cy.get(':nth-child(8) > .form-control').select('ROUND_ROBIN')
    cy.get(':nth-child(10) > .form-control').type('2')
    cy.get(':nth-child(11) > .form-control').type('5')
    cy.get(':nth-child(12) > .form-control').type('2')
    cy.get(':nth-child(13) > .form-control').select('PING')
    cy.get('#tNext').click()
    cy.get('.active > :nth-child(1) > :nth-child(1) > .form-control').type('matheus')
    cy.get('.active > :nth-child(1) > :nth-child(2) > .form-control').type('5')
    cy.get(':nth-child(1) > :nth-child(3) > .form-control').type('1')
    cy.get('.active > :nth-child(1) > :nth-child(4) > .form-control').type('2')
    cy.get('.active > :nth-child(1) > :nth-child(5) > .form-control').type('1')
    cy.get(':nth-child(7) > .btn').click()
    cy.get('.ng-scope > :nth-child(1) > .form-control').type('may')
    cy.get('.ng-scope > :nth-child(2) > .form-control').select('change_in_capacity')
    cy.get('.col-md-2 > .form-control').type('4')
    cy.get('.col-md-2 > .form-control').type('1')
    cy.get('#tNext').click()
    cy.get('.active > :nth-child(1) > .form-group > .btn').click()
    cy.get('.ng-scope > div[style="padding-left:0"] > .form-control').type('eu0')
    cy.get('.ng-scope > div[style="padding-right:0"] > .form-control').select('may')
    cy.get('.ng-scope > .table > tbody > tr > [style="padding-left:0"] > .form-control').type('10')
    cy.get('.ng-scope > .table > tbody > tr > :nth-child(2) > .form-control').type('10')
    cy.get('.ng-scope > .table > tbody > tr > :nth-child(3) > .form-control').type('1')
    cy.get('.ng-scope > .table > tbody > tr > :nth-child(4) > .form-control').select('ge')
    // cy.get('.btn-success').click()
})
