/// <reference types="cypress" />
import { loginPage } from '../../../util.js';

it('deve criar uma maquina virtual', () =>{
    loginPage()    
    cy.get('[ng-class="{active: main.activeRoute(\'virtual-machines\')}"] > a > .nav-label').click()
    // cy.server()
    // cy.route('GET', '**/vdc').as('ucloudVdc')
    // cy.get('[ng-disabled="!main.hasPermission(439822) || main.isReadOnly()"]').click()   
    cy.get(`[ng-class="{active: main.activeRoute('virtual-machines')}"] > .nav > :nth-child(1) > .ng-binding`).click() 
    // cy.wait('@ucloudVdc')
    cy.get('[ng-disabled="!main.hasPermission(439822) || main.isReadOnly()"]').click()
    cy.wait(6000)
    cy.get(':nth-child(8) > label > input').click()
    cy.get('#tNext').click()
    cy.get('#selectGovBillingType > .row > .form-control').select('Sob demanda por CPU')
    cy.get('#newVm-name').type('matheus30')
    cy.get('[ng-hide="createVM.noVDCs || createVM.newVm.cloudProvider == null"] > :nth-child(4) > .form-group > .form-control').select('coutoopenstack')
    cy.get('#tNext').click()
    cy.wait(5000)
    cy.get(`[ng-hide="createVM.newVm.cloudProvider == 'aws' || createVM.newVm.cloudProvider == 'google' || createVM.newVm.cloudProvider == 'ibm'"] > .form-group > .form-control`).select('CentOS-7-updated')
    cy.get('.col-md-12 > :nth-child(4) > .form-group > .form-control').select('C1-1vCPU-2GB-RAM : 1 vCPUs, 2 GB RAM, 1.5 GB HD')
    cy.wait(400)
    cy.get(`[ng-hide="createVM.newVm.cloudProvider == 'hyper-v' || createVM.newVm.cloudProvider == 'google'"] > .form-group > .form-control`).select('172.26.0.0/16 / services-subnet -', {force: true})
    cy.get('#tNext').click()
    cy.get(`[ng-hide="createVM.newVm.cloudProvider == 'hyper-v' || createVM.newVm.cloudProvider == 'aws' || createVM.newVm.cloudProvider == 'google' || createVM.newVm.cloudProvider == 'vcloud' || createVM.newVm.cloudProvider == 'ibm' || createVM.disableAuthType "] > .row > .form-group > .form-control`).select('Usar par de chave')
    cy.get(`[ng-hide="createVM.newVm.cloudProvider == 'azure'"] > .form-group > .form-control`).select('Escolher chave existente')
    cy.get(`[ng-show="createVM.newVm.cloudProvider != 'azure' && createVM.keyPairTypeSelected != null && createVM.keyPairTypeSelected.code == 0"] > .form-group > .ng-scope > .form-control`).select('coutopen')
    cy.get(`[ng-show="createVM.vdcChoosen.containerAllowed.type != 'hyper-v'"] > .form-group > div.ng-scope > .form-control`).select('coutotesteautomatizado')
    cy.get('#tNext').click()
    // aqui se quiser ter uma assinatura cy.get(`[ng-show="createVM.vdcChoosen.containerAllowed.type != 'hyper-v' || createVM.vdcChoosen.containerAllowed.type != 'google'"] > .form-group > div.ng-scope > .form-control`).select('1603')
    cy.get('#tNext').click()
    // cy.get(`.modal-footer > .btn-success`).first().click()
})

